### ISSUE TITLE
README code not working

### ISSUE THREAD

**Issue by NauticalMile64** [stsievert/python-drawnow#1]
I have tried to run the code you have in the README.md file. It complains that `approx` is not defined:

```
Traceback (most recent call last):
  File "drawnow_demo.py", line 17, in <module>
    x_hat = approx(x, k)
NameError: name 'approx' is not defined
```

which module is this supposed to be from? Could it be depricated?

**Comment by stsievert** [comment]
Good catch... I left that function out on purpose but that could be a mistake. I left it out because that function depends on the singular value decomposition, which is beyond the scope of the python-drawnow.

I'll edit the README to clarify this.

**Comment by stsievert** [comment]
README edited. The implementation of the README code can be found in [tests/test.py](https://github.com/scottsievert/python-drawnow/blob/master/tests/test.py)

**Comment by NauticalMile64** [comment]
Not yet working for me. When I add the line `from test import *` to the beginning of the file, another error emerges:

```
Traceback (most recent call last):
  File "drawnow_demo.py", line 3, in <module>
    from test import *
  File "C:\path\to\file\test.py", line 41, in <module>
    drawnow(draw_fig)
  File "C:\Python34\lib\site-packages\drawnow\drawnow.py", line 61, in drawnow
    else: plt.draw_all()
AttributeError: 'module' object has no attribute 'draw_all'
```

To be clear, I just used `pip` to install drawnow. I've just copied the relevant codes from your project, I have not cloned/forked the repo.

**Comment by stsievert** [comment]
Looks like you're running into an issue with matplotlib on [drawnow.py:61](https://github.com/scottsievert/python-drawnow/blob/master/drawnow/drawnow.py#L61). At the Python prompt, what does 

``` python
>>> import matplotlib.pyplot as plt
>>> plt.draw_all
```

result in?

**Comment by NauticalMile64** [comment]
I see. I updated matplotlib and it resolved the problem, thanks!

**Comment by stsievert** [comment]
👍

**Comment by antibody-br** [comment]
Thank you, after long searching I found that "updating matplotlib" is the solution. You save my day!

**Comment by wahajamjad95** [comment]
how do you update matplotlib ?? please guide
@NauticalMile64 
@antibody-br @stsievert

**Comment by stsievert** [comment]
`pip install --upgrade matplotlib`.

Looks like `plt.draw_all` was added in matplotlib  1.5: http://matplotlib.org/2.0.1/users/prev_whats_new/whats_new_1.5.html

**Comment by stsievert** [comment]
Updated `setup.py` so it uses the correct matplotlib version and uploaded to PyPI. `pip install drawnow` now gets the correct version of mpl.
