### ISSUE TITLE
Install with python 3

### ISSUE THREAD

**Issue by bogbasic** [stsievert/python-drawnow#10]
Just a comment on the documentation. To install for use with python 3, the following commands are needed.

sudo apt-get install python3-pip
sudo pip3 install drawnow

That's it, thanks for looking.

**Comment by stsievert** [comment]
Closed. Now there's this snippet in the readme:

> Option 2 assumes a working Python installation with pip. I suggest Anaconda's distribution: https://www.anaconda.com/distribution/ For other options, see https://realpython.com/installing-python/.
