### ISSUE TITLE
Errors when executing code

### ISSUE THREAD

**Issue by jsanchezq1** [stsievert/python-drawnow#11]
These errors occur:

IndexError                                Traceback (most recent call last)
<ipython-input-3-3c6425b246ee> in <module>
     36 k_values = around(logspace(0.1, log10(64), num=10)).astype('int')
     37 for k in k_values:
---> 38     x_hat = approx(x, k)
     39     drawnow(draw_fig, stop_on_close=True)

<ipython-input-3-3c6425b246ee> in approx(x, k)
      8     y = zeros_like(x)
      9     for i in arange(4):
---> 10         u, sigmas, v = svd(x[:,:,i])
     11         sigmas[k:] = 0
     12 

IndexError: index 3 is out of bounds for axis 2 with size 3

Could you please help me

**Comment by stsievert** [comment]
I presume you're running `test.py` off the master branch. I can't reproduce this error; running `test.py` on the master branch works for me.
