### ISSUE TITLE
Showing the plot only once?

### ISSUE THREAD

**Issue by sieumap43** [stsievert/python-drawnow#12]
Is there a feature in which the plot is updated instead of showing multiple plots? I mean the new points in the new for loop iterations are added to the original plot, instead of being drawn in new plots.
If not is there atleast a way where old plots are deleted on the appearance of a new plot so it can give the illusion of the original plot being updated?

**Comment by stsievert** [comment]
> the plot is updated instead of showing multiple plots

Yes, that's what this tool does by default. That's what the example on the README does and what the code indicates:
https://github.com/stsievert/python-drawnow/blob/668109ee7f8425189125785853bc5c6f35352232/drawnow/drawnow.py#L59-L60

Are you getting different behavior?

**Comment by sieumap43** [comment]
![code_from_testpy](https://user-images.githubusercontent.com/26580120/81903948-da7c6180-95c2-11ea-947c-99cc7812f825.png)
![code_from_stackoverflow](https://user-images.githubusercontent.com/26580120/81903945-d8b29e00-95c2-11ea-847c-2b96e2607606.png)
Yeah. I tried the example from the README in Spyder and here is the result. It is the same when I tried it in Jupyter Notebook. I also tried setting the parameter show_once to both False and True but the results are also the same.
The second picture is of a piece of code I found on stackoverflow using your library but the result is still identical with a bunch of new plots instead of one plot.

**Comment by stsievert** [comment]
Thanks for the clarification. I didn't really develop for Jupyter/Spyder, but this code works for me in Jupyter and their console if I enter this magic command before running `test.py`:

``` 
%matplotlib
```

This opens up a separate window with the animation with the default Matplotlib GUI (not the inline GUI as used in Jupyter/QTConsole).
