### ISSUE TITLE
DOC: Typos in `drawnow` docstring

### ISSUE THREAD

**Issue by afvincent** [stsievert/python-drawnow#2]
In `drawnow.py`, in the docstring of `drawnow`:
- l. 29, "Occaisonally" should be "Occasionally"
- l. 18, not sure about this one but shoudn't "the list of parameters to pass `draw_fig()`" be "the list of parameters to pass to `draw_fig()`"?

**Comment by stsievert** [comment]
If you see typos feel free to submit a pull request.
